// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzsr86B3bRMXD_k3y3dpRvWo7A2yPM2C0',
    appId: '1:660392431107:web:be97b38908a0c48e6d0836',
    messagingSenderId: '660392431107',
    projectId: 'weather-578f8',
    authDomain: 'weather-578f8.firebaseapp.com',
    storageBucket: 'weather-578f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaXFOxgisDUoVkdd2ONtg3lM0YnHE5H4s',
    appId: '1:660392431107:android:2f2255be02d503456d0836',
    messagingSenderId: '660392431107',
    projectId: 'weather-578f8',
    storageBucket: 'weather-578f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx3SaJiGiISY_YMhD5LEpiVP2td2Lwywk',
    appId: '1:660392431107:ios:9cab7c15132429956d0836',
    messagingSenderId: '660392431107',
    projectId: 'weather-578f8',
    storageBucket: 'weather-578f8.appspot.com',
    iosBundleId: 'com.shokhrukhbek.weatherService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx3SaJiGiISY_YMhD5LEpiVP2td2Lwywk',
    appId: '1:660392431107:ios:d07dce9b3fa7feb56d0836',
    messagingSenderId: '660392431107',
    projectId: 'weather-578f8',
    storageBucket: 'weather-578f8.appspot.com',
    iosBundleId: 'com.shokhrukhbek.weatherService.RunnerTests',
  );
}
